import Nav from "@components/Nav"
import Footer from "@components/Footer";
import "@styles/globals.css";
import Follow from "@components/Follow";

export const metadata = {
  title: 'Medicare - Your one stop partner for health',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="main -z-[1]">
          <div className="gradient"></div>
        </div>


        <div className="z-10 box_size mx-auto relative min-h-[100vh] flex justify-between flex-col">
          <div className="w-full box">
            <Nav />
            {children}
            <Follow />
          </div>
            <Footer/>
        </div>
      </body>
    </html>
  )
}
