import Nav from "@components/Nav"

export const metadata = {
  title: 'Medicare - Your one stop partner for health',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="main -z-[1]">
          <div className="gradient"></div>
        </div>


        <div className="z-10 box_size mx-auto relative">
          <div className="w-full box">
            <Nav />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
